{
  "pod": "zukunft.com",
  "type": "sys_log_list",
  "user_id": 3,
  "user": "zukunft.com system test",
  "version": "0.0.3",
  "body": [
    {
      "id": 1,
      "user": "zukunft.com system test",
      "text": "the log text that describes the problem for the user or system admin",
      "trace": "the technical trace back description for debugging",
      "prg_part": "name of the function that has caused the exception",
      "status": 2
    },
    {
      "id": 2,
      "user": "zukunft.com system test",
      "text": "the log 2 text that describes the problem for the user or system admin",
      "trace": "the technical trace 2 back description for debugging",
      "prg_part": "name 2 of the function that has caused the exception",
      "status": 3
    }
  ]
}